version: '3.7'

services:
  nginx:
    container_name: nginx-app
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
  web:
    container_name: my-flask
    build: .
    # command: gunicorn -b 0.0.0.0:8000 - app:app
    volumes:
      - ./:/app
      - ./shared:/shared
      - app-data:/app-persistent
      # app_data:/app
    # environment:
    # - DATABASE_HOST=db
    
volumes:
     app-data:
